name: cli_util
version: 0.3.0-nullsafety.0
description: A library to help in building Dart command-line apps.
homepage: https://github.com/dart-lang/cli_util

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety
  path: ^1.8.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
